POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "Varsh",
    "password": "Varsh@123"
}
###
POST  http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "Varsh",
    "password": "Varsh@123"
}
###
POST http://127.0.0.1:8000/api/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NjIwODgyNCwiaWF0IjoxNzQ2MTIyNDI0LCJqdGkiOiIwYzA4MGZkNWE3NTg0OGFjYjM1ZDY5ODEwY2QxN2YyNiIsInVzZXJfaWQiOjcsInVzZXJuYW1lIjoiVmFyc2gifQ.HOQreJADpUa2zr32fBly6aMigbyb2fj45IF9etNIKHI"
}
###
GET http://127.0.0.1:8000/api/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MTIyNzk0LCJpYXQiOjE3NDYxMjI0OTQsImp0aSI6ImNlZGJlOWM2NDk0ZTRmNmZiODI1YjZlMzliZGUxYmI4IiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJWYXJzaCJ9.fvD7N7bLrEbm06HPg-0SLFp9l-uDvztKz1msMFiKaAQ

###
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MTIyNzk0LCJpYXQiOjE3NDYxMjI0OTQsImp0aSI6ImNlZGJlOWM2NDk0ZTRmNmZiODI1YjZlMzliZGUxYmI4IiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJWYXJzaCJ9.fvD7N7bLrEbm06HPg-0SLFp9l-uDvztKz1msMFiKaAQ

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NjIwODk1NywiaWF0IjoxNzQ2MTIyNTU3LCJqdGkiOiJiYjMwYjZhMzRmYzY0ZTA0ODBhMDgyZmI5MzZmMDRhNiIsInVzZXJfaWQiOjcsInVzZXJuYW1lIjoiVmFyc2gifQ.vsQz2wmzdzWiG32dTxbMshSIOpHXQQidmPoND0LZjGA"
}