###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "Walter",
    "password": "Walter@123"
}
###
POST  http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "Walter",
    "password": "Walter@123"
}
###
POST http://127.0.0.1:8000/api/refresh/
Content-Type: application/json

{
    "refresh": "YOUR_REFRESH_TOKEN"
}

###
GET http://127.0.0.1:8000/api/profile/
Authorization: Bearer <YOUR_ACCESS_TOKEN>

###
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Bearer <YOUR_ACCESS_TOKEN>

{
    "refresh": "YOUR_REFRESH_TOKEN"
}

###

POST http://localhost:8000/api/password-reset/
Content-Type: application/json

{
  "username": "Walter"
}

###

POST http://localhost:8000/api/password-reset-confirm/
Content-Type: application/json

{
  "token": "RESET_TOKEN",
  "new_password": "Walter@2005"
}
